use_frameworks!

target 'HouJia_Example' do
  pod 'HouJia', :path => '../'

  target 'HouJia_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
#      puts "##### target: #{target} #####"
      target.build_configurations.each do |config|
#        puts "##### config: #{config} #####"
        if config.name == 'Test'
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-DDEBUG', '-DTEST']
        else
          config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
        end
      end
    end
end
